### PR TITLE
Upgrade project to Ember & Ember CLI 3.3.0

### PR DESCRIPTION
**Pull request by BrianSipple**
While trying to get rid of some Babel 5.x deprecation errors, I felt like there was a good opportunity to give the entire structure a 3.3.x upgrade. 

The only major change to the addon code itself involves [using the `owner.factoryFor` API](https://github.com/miguelcobain/ember-dynamic-render-template/compare/master...BrianSipple:update-project-structure?expand=1#diff-53fe41c745d6dedbd963374d32070c9eR25) to create an instance of the rendered component. 

I also added a small dummy app example that demos binding to a hash property.

### CODE REVIEW

**Comment by BrianSipple** [comment]
🤔 Travis seems to be failing in the manner of https://github.com/testem/testem/issues/1021

**Comment by miguelcobain** [comment]
Thanks a lot for the PR!
This failure is unfortunate.

Tried to restart jobs. Maybe the failures aren't consistent.

**Comment by CygnusRoboticus** [comment]
It's failing due to `owner.factoryFor('component:render-template')`, which seemingly creates an infinite rendering loop in all of the LTS versions. Adding a `component:render-template-result` resolves it; no need for a `.hbs`.

**Comment by BrianSipple** [comment]
Thanks for figuring this out, @CygnusRoboticus -- I really like that solution! I just pushed it up and rebased... looks like we're all green. (cc @miguelcobain)

**Comment by miguelcobain** [comment]
@BrianSipple @CygnusRoboticus thanks a lot for the help here!

**Comment by miguelcobain** [comment]
`ember-dynamic-render-template@0.0.4` is published

**Pull request merged**
